env: "development"
server:
  debug: true
  port: 8080
  host: "0.0.0.0"
database:
  host: "localhost"
  port: 5432
  name: "dashbeam_db"
  user: "postgres"
  password: "postgres"
  sslmode: "disable"
  timezone: "UTC"
auth:
  jwt_secret_key: ""
  access_token_expiry: 24h
